In [ ]:
print("a")

In [ ]:
import importlib
import imageio.v2 as imageio
from patient import patient
import glob

# https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6ACUZJ

In [ ]:
import importlib
import imageio.v2 as imageio
from patient import patient
import glob

# https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6ACUZJ

from tqdm.notebook import tqdm
for vol_path in tqdm(glob.glob("./data/*")):
    if "__" in vol_path:
        continue
    vol = vol_path.split("/")[-1]
    print(vol)
    # print(vol)
    p = patient.patient(name=vol)
# imageio.mimsave(f"pics/drr.gif", p.drr.img)

In [ ]:
from patient import patient
import imageio.v2 as imageio
import cupy as cp

p = patient.patient(name="4411469")

a = 180


imageio.imsave("pics/ct.png", cp.asnumpy(p.ct.img[a]))
# imageio.imsave("pics/test2.png", p.get_resized_fbp(p.get_equiv(a, plot=True)[0]))
imageio.imsave("pics/test2.png", cp.asnumpy(p.get_equiv_fbp(a)))

imgct = imageio.imread("pics/ct.png").astype("float32")
imgrec = imageio.imread("pics/test2.png").astype("float32")

imageio.imsave("pics/diff.png", imgct - imgrec)

## Xray set

In [9]:
import importlib
from xray import xray
import imageio.v2 as imageio
import cv2   
import cupy as cp
import numpy as np

importlib.reload(xray)

xrayset = xray.xrayset(
        name="__phantom",
        sheets=450,
        voltage=120,
        height=1024,
        output_height=500
    )
%slack

  0%|          | 0/450 [00:00<?, ?it/s]

500 500


  0%|          | 0/112500000 [00:00<?, ?it/s]

[189 194 205 ...   0   0   0]
[185 192 206 ...   0   0   0]
[194 199 208 ...   0   0   0]
[176 184 203 ...   0   0   0]
[187 193 207 ...   0   0   0]
[189 195 208 ...   0   0   0]
[194 199 208 ...   0   0   0]
[187 193 207 ...   0   0   0]
[187 192 203 ...   0   0   0]
[186 191 201 ...   0   0   0]
[185 190 199 ...   0   0   0]
[174 181 196 ...   0   0   0]
[181 187 199 ...   0   0   0]
[182 187 199 ...   0   0   0]
[172 179 194 ...   0   0   0]
[175 181 195 ...   0   0   0]
[183 188 197 ...   0   0   0]
[188 192 200 ...   0   0   0]
[182 188 200 ...   0   0   0]
[180 187 201 ...   0   0   0]
[185 189 199 ...   0   0   0]
[174 181 198 ...   0   0   0]
[177 183 197 ...   0   0   0]
[179 185 199 ...   0   0   0]
[184 190 201 ...   0   0   0]
[177 184 198 ...   0   0   0]
[169 178 196 ...   0   0   0]
[174 182 199 ...   0   0   0]
[201 203 206 ...   0   0   0]
[174 182 198 ...   0   0   0]
[177 184 198 ...   0   0   0]
[187 191 201 ...   0   0   0]
[179 185 197 ...   0   0   0]
[177 185 2

In [ ]:
# imgs = []
# for img in xrayset.img:
#     imgs.append(cp.asnumpy(img).astype("uint8").astype('uint8'))
# imageio.mimsave("x.gif", imgs)

Lossy conversion from float64 to uint8. Range [133.2235854625946, 222.60539599449805]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [133.2235854625946, 222.60539599449805]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [133.2235854625946, 222.60539599449805]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [133.2235854625946, 219.21328847591545]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [133.2235854625946, 222.60539599449805]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [133.2235854625946, 222.60539599449805]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [133.2235854625946, 219.21328847591545]. C

In [10]:
import fbp.tompy as fbp
import cupy as cp

# fbp from xrayset
rec2 = fbp.fbpset(
        xrayset,
        height=300,
        # adjust_alpha=4.,
        # adjust_beta=-120.,
        # angle=1,
        rotate=211,
        load_all=False
    )

# print(cp.asnumpy(rec2.get(5)))
# imageio.imsave("test.png", cp.asnumpy(rec2.get(5)))
imageio.imsave("x.png", cp.asnumpy(rec2.x.img[150]))

Lossy conversion from float64 to uint8. Range [53.278304758206225, 255.0]. Convert image to uint8 prior to saving to suppress this warning.


In [11]:
print(rec2.get(300))
c = imageio.imread("colorsample.png")
imageio.imsave("test.png", cp.asnumpy(rec2.get(300)))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
